"""Break-action registry (phase 9, milestone 41).

A break-fix lab's starting state is **declarative data, never instructor-written shell**:

    lab.yaml -> break-action compiler -> setup execution

Each action is a typed operation with a Pydantic parameter model (the Lab Builder generates its form from
that model), the emulator operations it performs (validated against the engine capability files at import),
a deterministic bash compiler, and a one-line summary for the Broken State Summary.

`compile_actions` is the only place that turns actions into shell. It is pure and order-preserving, so the
same lab.yaml always produces the same setup script (and therefore the same broken state).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from pydantic import BaseModel, ConfigDict


class ActionParams(BaseModel):
    model_config = ConfigDict(extra="forbid")


Reads = tuple[str, ...] | Callable[[Any], tuple[str, ...]]


@dataclass(frozen=True)
class BreakActionDef:
    type: str
    params_model: type[ActionParams]
    service: str
    reads: Reads
    compile: Callable[[Any], list[str]]
    summary: Callable[[Any], str]

    def reads_for(self, params: Any) -> tuple[str, ...]:
        return self.reads(params) if callable(self.reads) else self.reads


REGISTRY: dict[str, BreakActionDef] = {}
_loaded = False


def register(defn: BreakActionDef) -> BreakActionDef:
    if defn.type in REGISTRY:
        raise RuntimeError(f"duplicate break action {defn.type}")
    REGISTRY[defn.type] = defn
    return defn


def load_all() -> None:
    global _loaded
    if _loaded:
        return
    from . import actions  # noqa: F401  (registers the catalogue)
    _loaded = True


def get(type_: str) -> BreakActionDef:
    load_all()
    if type_ not in REGISTRY:
        raise KeyError(type_)
    return REGISTRY[type_]


def compile_actions(specs: list[dict[str, Any]]) -> str:
    """The setup script for a list of already-rendered break actions. Raises ValueError for unknown types
    or invalid parameters (callers validate first, so this is a safety net)."""
    load_all()
    lines = ["#!/bin/bash",
             "# Generated by the CloudLabs break-action compiler from lab.yaml break_actions.",
             "# Do not edit: change the actions in the Lab Builder (or lab.yaml) instead.",
             "set -euo pipefail", ""]
    for i, spec in enumerate(specs, 1):
        type_ = str(spec.get("type", ""))
        defn = REGISTRY.get(type_)
        if defn is None:
            raise ValueError(f"unknown break action {type_!r}")
        params = defn.params_model.model_validate({k: v for k, v in spec.items() if k != "type"})
        lines.append(f"# {i}. {type_}")
        lines += defn.compile(params)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
