"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 19:28:22.337124
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('labs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('runners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('max_sandboxes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('student', 'instructor', 'admin', name='role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('short_id', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('short_id')
    )
    op.create_table('course_staff',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('enrolments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('lab_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('yaml_text', sa.Text(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'version')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('lab_version_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allow_late', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('grade_policy', sa.String(length=10), server_default='best', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lab_version_id'], ['lab_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_table('lab_version_bundles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lab_version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['lab_version_id'], ['lab_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_version_id', 'kind')
    )
    op.create_table('lab_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('lab_version_id', sa.UUID(), nullable=False),
    sa.Column('runner_id', sa.String(length=64), nullable=False),
    sa.Column('env', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('REQUESTED', 'PROVISIONING', 'READY', 'RESETTING', 'SUBMITTING', 'SUBMITTED', 'TERMINATING', 'TERMINATED', 'FAILED', name='session_state'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('state_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ttl_minutes', sa.Integer(), nullable=False),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('emulator_endpoint', sa.String(length=255), nullable=True),
    sa.Column('terminal_endpoint', sa.String(length=255), nullable=True),
    sa.Column('ttyd_cred_enc', sa.Text(), nullable=True),
    sa.Column('image_digest', sa.String(length=100), nullable=True),
    sa.Column('terminal_image_digest', sa.String(length=100), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['lab_version_id'], ['lab_versions.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_sessions_user_id'), 'lab_sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_state', 'lab_sessions', ['state'], unique=False)
    op.create_index('uq_active_session_per_assignment', 'lab_sessions', ['user_id', 'assignment_id'], unique=True, postgresql_where=sa.text("state IN ('REQUESTED','PROVISIONING','READY','RESETTING','SUBMITTING')"))
    op.create_table('student_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('extra_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('close_at_override', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_overrides_assignment_id'), 'student_overrides', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_overrides_user_id'), 'student_overrides', ['user_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('lab_version_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('counts', sa.Boolean(), nullable=False),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('grader_version', sa.String(length=20), nullable=False),
    sa.Column('emulator_image_digest', sa.String(length=100), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['lab_version_id'], ['lab_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('user_id', 'assignment_id', 'attempt_no')
    )
    op.create_index(op.f('ix_attempts_assignment_id'), 'attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_events_session_id'), 'session_events', ['session_id'], unique=False)
    op.create_table('terminal_tickets',
    sa.Column('ticket_hash', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_hash')
    )
    op.create_index(op.f('ix_terminal_tickets_session_id'), 'terminal_tickets', ['session_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('grader_version', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_attempt_id'), 'grades', ['attempt_id'], unique=False)
    op.create_table('grading_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_evidence_attempt_id'), 'grading_evidence', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_grading_evidence_session_id'), 'grading_evidence', ['session_id'], unique=False)
    op.create_table('task_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('marks_awarded', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('marks_possible', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_results_attempt_id'), 'task_results', ['attempt_id'], unique=False)
    # ### end Alembic commands ###
    _append_only_and_grants()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_results_attempt_id'), table_name='task_results')
    op.drop_table('task_results')
    op.drop_index(op.f('ix_grading_evidence_session_id'), table_name='grading_evidence')
    op.drop_index(op.f('ix_grading_evidence_attempt_id'), table_name='grading_evidence')
    op.drop_table('grading_evidence')
    op.drop_index(op.f('ix_grades_attempt_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_terminal_tickets_session_id'), table_name='terminal_tickets')
    op.drop_table('terminal_tickets')
    op.drop_index(op.f('ix_session_events_session_id'), table_name='session_events')
    op.drop_table('session_events')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_assignment_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_student_overrides_user_id'), table_name='student_overrides')
    op.drop_index(op.f('ix_student_overrides_assignment_id'), table_name='student_overrides')
    op.drop_table('student_overrides')
    op.drop_index('uq_active_session_per_assignment', table_name='lab_sessions', postgresql_where=sa.text("state IN ('REQUESTED','PROVISIONING','READY','RESETTING','SUBMITTING')"))
    op.drop_index('ix_sessions_state', table_name='lab_sessions')
    op.drop_index(op.f('ix_lab_sessions_user_id'), table_name='lab_sessions')
    op.drop_table('lab_sessions')
    op.drop_table('lab_version_bundles')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('lab_versions')
    op.drop_table('idempotency_keys')
    op.drop_table('enrolments')
    op.drop_table('course_staff')
    op.drop_table('users')
    op.drop_table('runners')
    op.drop_table('labs')
    op.drop_table('courses')
    # ### end Alembic commands ###


APPEND_ONLY = ("attempts", "task_results", "grading_evidence", "grades", "session_events",
               "student_overrides", "lab_versions", "lab_version_bundles")


def _append_only_and_grants() -> None:
    """PLAN §6: append-only tables reject UPDATE/DELETE/TRUNCATE via triggers, and the app role has no
    UPDATE/DELETE/TRUNCATE grant on them. Only the owner role (maintenance/demo reset) can disable the
    triggers explicitly."""
    op.execute("""
        CREATE OR REPLACE FUNCTION cloudlabs_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'table % is append-only (% rejected)', TG_TABLE_NAME, TG_OP
            USING ERRCODE = 'insufficient_privilege';
        END $$;
    """)
    for t in APPEND_ONLY:
        op.execute(f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                   f"FOR EACH ROW EXECUTE FUNCTION cloudlabs_append_only()")
        op.execute(f"CREATE TRIGGER {t}_no_truncate BEFORE TRUNCATE ON {t} "
                   f"FOR EACH STATEMENT EXECUTE FUNCTION cloudlabs_append_only()")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cloudlabs_app")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cloudlabs_app")
    for t in APPEND_ONLY:
        op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON {t} FROM cloudlabs_app")
    op.execute("REVOKE ALL ON alembic_version FROM cloudlabs_app")
